language: node_js
node_js: 11
branches:
  only: master
cache: yarn
install:
  - exit 0
script:
  - exit 0
deploy:
  github-token:
    secure: I1/EdK1VXg3fTmvzkEmQjJqK6LIC+O2ZG3d1eS9xrXZN8m/rii25DTg6S+JheU+XyXmCarr5lnfx1Laxwl7VmKFDbGSmUHrAqpuQU+DHJjp7wQoWrxbJD9O0PQllcit/HCK+Ac7xeVkslqVBZUDBkVkBzX1D6Ej66TZFFyZ4CwPdXM9RRHNjExSPeMZ3OjtTx8+3MM6z0tvIxJp5+lGm/SaG/yY46cwiW8SsZzTFd2lv7ZuYU1+T44UW4a+irPZimL/9xAsGjrySmcEPD6SsAD2J94EdvsyGCxwAs2GiAzXRzMzZ2pz0k1yr1VDFm9DxEjcPHGe5bilLhwPz5JGPV4STyzoy5AxgLISmGmokL5J9TnMTenSOaDKX2gFNt4XNoJ5hfWjurufjukESxc3Vjbju98wCe1Fw1/148S4Qu2nWZHj6YW0rBJZONFqhWUI0PFwOloQX1SQvO7CetXuRXJ0HD4of3r7f2jie/pNqt453Mc47RUSBJFjROZWZrRA6Ifa5jazj1IFsKE37qrQH2ZGW20GaWl0FEfgvc5eKbqFIQv+w9s8V5SIGz5PLCZhe7ohhOYOf27orGFPnoa6ws2v3iVpiQ8YzOYq52CN0GI/MPLRdGLuBi+1DXzfyCJV18p1J60D3XuBkkvSOs3fI5GeBGeUraY524PKXaVbl0+E=
  keep-history: true
  local-dir: src
  on:
    branch: master
  provider: pages
  skip-cleanup: true
  target-branch: gh-pages
